[package]
description = "A pure rust interface to the LabJack T-series via Modbus TCP"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "tokio_labjack"
repository = "https://github.com/nschrading/tokio_labjack"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tokio_labjack_lib"
path = "src/lib.rs"

[[bin]]
name = "tokio_labjack"
path = "src/bin.rs"

[dependencies]
env_logger = "*"
log = "*"
tokio = { version = "1.4", features = ["rt", "macros"] }
tokio-modbus = { version = "*", default-features = false, features = ["tcp"] }
